
import { Job, Category, Location } from '../types';

export const categories: Category[] = [
  { id: 1, name: 'Engineering', slug: 'engineering' },
  { id: 2, name: 'Medical', slug: 'medical' },
  { id: 3, name: 'Teaching', slug: 'teaching' },
  { id: 4, name: 'Banking', slug: 'banking' },
  { id: 5, name: 'Defense', slug: 'defense' },
  { id: 6, name: 'Police', slug: 'police' },
  { id: 7, name: 'IT & Technical', slug: 'it-technical' },
  { id: 8, name: 'Administration', slug: 'administration' },
];

export const locations: Location[] = [
  { id: 1, city: 'New Delhi', state: 'Delhi', slug: 'new-delhi' },
  { id: 2, city: 'Mumbai', state: 'Maharashtra', slug: 'mumbai' },
  { id: 3, city: 'Pune', state: 'Maharashtra', slug: 'pune' },
  { id: 4, city: 'Bengaluru', state: 'Karnataka', slug: 'bengaluru' },
  { id: 5, city: 'Chennai', state: 'Tamil Nadu', slug: 'chennai' },
  { id: 6, city: 'Hyderabad', state: 'Telangana', slug: 'hyderabad' },
  { id: 7, city: 'Kolkata', state: 'West Bengal', slug: 'kolkata' },
  { id: 8, city: 'Lucknow', state: 'Uttar Pradesh', slug: 'lucknow' },
  { id: 9, city: 'Jaipur', state: 'Rajasthan', slug: 'jaipur' },
  { id: 10, city: 'Ahmedabad', state: 'Gujarat', slug: 'ahmedabad' },
];

const today = new Date();
const addDays = (date: Date, days: number) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result.toISOString();
};

export const jobs: Job[] = [
  {
    id: 1,
    title: 'Software Engineer (SDE-1)',
    department: 'Ministry of Information Technology',
    category: 'it-technical',
    location: 'new-delhi',
    state: 'Delhi',
    salaryMin: 70000,
    salaryMax: 90000,
    experienceRequired: '1-3 years',
    educationRequired: 'B.E/B.Tech in CS/IT',
    applicationDeadline: addDays(today, 30),
    postedDate: addDays(today, -5),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Seeking a skilled Software Engineer to develop and maintain critical government applications. Strong knowledge of Java and Python required.',
    applicationUrl: '#',
  },
  {
    id: 2,
    title: 'Junior Resident Doctor',
    department: 'All India Institute of Medical Sciences (AIIMS)',
    category: 'medical',
    location: 'new-delhi',
    state: 'Delhi',
    salaryMax: 85000,
    experienceRequired: '0-1 year',
    educationRequired: 'MBBS',
    applicationDeadline: addDays(today, 7),
    postedDate: addDays(today, -2),
    jobType: 'contract',
    employmentType: 'full-time',
    description: 'AIIMS Delhi is recruiting Junior Resident Doctors for various departments. This is a one-year contractual position.',
    applicationUrl: '#',
  },
  {
    id: 3,
    title: 'Probationary Officer (PO)',
    department: 'State Bank of India',
    category: 'banking',
    location: 'mumbai',
    state: 'Maharashtra',
    salaryMin: 55000,
    salaryMax: 65000,
    experienceRequired: 'Not Required',
    educationRequired: 'Graduate in any discipline',
    applicationDeadline: addDays(today, 45),
    postedDate: addDays(today, -1),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Join SBI as a Probationary Officer. A challenging role with excellent career growth opportunities in the banking sector.',
    applicationUrl: '#',
  },
  {
    id: 4,
    title: 'Assistant Professor of Physics',
    department: 'University of Mumbai',
    category: 'teaching',
    location: 'mumbai',
    state: 'Maharashtra',
    salaryMin: 60000,
    salaryMax: 75000,
    experienceRequired: '2+ years teaching',
    educationRequired: 'Ph.D. in Physics',
    applicationDeadline: addDays(today, 25),
    postedDate: addDays(today, -10),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'The Department of Physics invites applications for the post of Assistant Professor. Candidates must have a strong research background.',
    applicationUrl: '#',
  },
  {
    id: 5,
    title: 'Technical Officer',
    department: 'ISRO Satellite Centre',
    category: 'engineering',
    location: 'bengaluru',
    state: 'Karnataka',
    salaryMin: 80000,
    salaryMax: 110000,
    experienceRequired: '5+ years',
    educationRequired: 'M.E/M.Tech in Mechanical/Aerospace',
    applicationDeadline: addDays(today, 50),
    postedDate: addDays(today, -3),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Contribute to India\'s space program. Looking for experienced engineers for satellite design and development.',
    applicationUrl: '#',
  },
  {
    id: 6,
    title: 'Constable (General Duty)',
    department: 'Rajasthan Police',
    category: 'police',
    location: 'jaipur',
    state: 'Rajasthan',
    salaryMin: 25000,
    salaryMax: 35000,
    experienceRequired: 'Not Required',
    educationRequired: '12th Pass',
    applicationDeadline: addDays(today, 20),
    postedDate: addDays(today, -8),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Serve the state of Rajasthan. Recruitment for constables is now open. Physical fitness test is mandatory.',
    applicationUrl: '#',
  },
  {
    id: 7,
    title: 'Clerk / Office Assistant',
    department: 'Lucknow High Court',
    category: 'administration',
    location: 'lucknow',
    state: 'Uttar Pradesh',
    salaryMin: 30000,
    salaryMax: 40000,
    educationRequired: 'Graduate, Computer Proficiency',
    applicationDeadline: addDays(today, 15),
    postedDate: addDays(today, -12),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Administrative positions open at the Lucknow High Court. Typing speed of 30 WPM in English is required.',
    applicationUrl: '#',
  },
  {
    id: 8,
    title: 'Data Entry Operator',
    department: 'National Health Mission',
    category: 'it-technical',
    location: 'pune',
    state: 'Maharashtra',
    salaryMin: 22000,
    salaryMax: 28000,
    experienceRequired: '6 months',
    educationRequired: '12th Pass + Computer Diploma',
    applicationDeadline: addDays(today, 10),
    postedDate: addDays(today, -4),
    jobType: 'temporary',
    employmentType: 'full-time',
    description: 'Temporary position for a data entry operator to support NHM projects in Pune. Contract is for 11 months.',
    applicationUrl: '#',
  },
    {
    id: 9,
    title: 'Civil Engineer',
    department: 'Public Works Department (PWD)',
    category: 'engineering',
    location: 'chennai',
    state: 'Tamil Nadu',
    salaryMin: 65000,
    salaryMax: 80000,
    experienceRequired: '3-5 years',
    educationRequired: 'B.E in Civil Engineering',
    applicationDeadline: addDays(today, 35),
    postedDate: addDays(today, -6),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'PWD Chennai is looking for experienced Civil Engineers for infrastructure projects. Knowledge of local building codes is essential.',
    applicationUrl: '#',
  },
  {
    id: 10,
    title: 'Lieutenant',
    department: 'Indian Army (SSC Tech)',
    category: 'defense',
    location: 'new-delhi', // Pan-India posting
    state: 'Delhi',
    salaryMin: 56100,
    salaryMax: 177500,
    experienceRequired: 'Not Required',
    educationRequired: 'Engineering Graduate',
    applicationDeadline: addDays(today, 60),
    postedDate: addDays(today, -15),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Join the Indian Army as a Short Service Commissioned Technical Officer. Serve the nation with pride and honor.',
    applicationUrl: '#',
  },
  {
    id: 11,
    title: 'Cyber Security Analyst',
    department: 'National Informatics Centre (NIC)',
    category: 'it-technical',
    location: 'hyderabad',
    state: 'Telangana',
    salaryMin: 75000,
    salaryMax: 95000,
    experienceRequired: '2+ years in Cybersecurity',
    educationRequired: 'B.Tech/MCA',
    applicationDeadline: addDays(today, 40),
    postedDate: addDays(today, -9),
    jobType: 'contract',
    employmentType: 'full-time',
    description: 'Protect national digital infrastructure. Seeking analysts with experience in network security, ethical hacking, and incident response.',
    applicationUrl: '#',
  },
  {
    id: 12,
    title: 'Primary School Teacher',
    department: 'Kolkata Municipal Corporation',
    category: 'teaching',
    location: 'kolkata',
    state: 'West Bengal',
    salaryMin: 35000,
    salaryMax: 45000,
    experienceRequired: '0-2 years',
    educationRequired: 'D.El.Ed with Graduation',
    applicationDeadline: addDays(today, 28),
    postedDate: addDays(today, -11),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Recruitment for primary school teachers in KMC-run schools. Candidates must have passed the Teacher Eligibility Test (TET).',
    applicationUrl: '#',
  },
  {
    id: 13,
    title: 'Forest Range Officer',
    department: 'Gujarat Forest Department',
    category: 'administration',
    location: 'ahmedabad',
    state: 'Gujarat',
    salaryMin: 40000,
    salaryMax: 55000,
    experienceRequired: 'Not Required',
    educationRequired: 'B.Sc in Forestry/Agriculture',
    applicationDeadline: addDays(today, 32),
    postedDate: addDays(today, -14),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Protect and manage the forest resources of Gujarat. A challenging field job for nature lovers.',
    applicationUrl: '#',
  },
  {
    id: 14,
    title: 'Specialist Officer (IT)',
    department: 'Bank of Baroda',
    category: 'banking',
    location: 'bengaluru',
    state: 'Karnataka',
    salaryMin: 60000,
    salaryMax: 80000,
    experienceRequired: '2 years',
    educationRequired: 'B.E/B.Tech in CS/IT',
    applicationDeadline: addDays(today, 18),
    postedDate: addDays(today, -7),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Bank of Baroda requires IT Specialist Officers for their technology centers. Experience in banking software is preferred.',
    applicationUrl: '#',
  },
  {
    id: 15,
    title: 'Staff Nurse',
    department: 'JIPMER',
    category: 'medical',
    location: 'chennai', // This is a bit of a stretch, JIPMER is in Puducherry, let's use Chennai for the example
    state: 'Tamil Nadu',
    salaryMin: 44900,
    salaryMax: 60000,
    experienceRequired: '1 year',
    educationRequired: 'B.Sc Nursing',
    applicationDeadline: addDays(today, 4),
    postedDate: addDays(today, -1),
    jobType: 'permanent',
    employmentType: 'full-time',
    description: 'Join a premier medical institution as a Staff Nurse. Urgent requirement.',
    applicationUrl: '#',
  },
];
